[project]
name = "04-analytics-engineering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-bigquery>=1.11.0",
    "dbt-core>=1.11.4",
    "google-cloud-storage>=3.1.1",
]
